dromara/newcar

- README.md
- doc/README.md
- doc/objects/README.md
Corrected some poor English mistakes and made the documentations more formally.
> [chore] updated READMEs

- README.md
- examples/canvaskit-test/index.html
- examples/canvaskit-test/main.ts
- examples/conveyer-belt-model/index.ts
- examples/test/index.ts
- packages/basic/src/objects/figures/dot.ts
- packages/basic/src/objects/maths/number-plane.ts
-    add the dot.ts in packages\basic\src\objects\figures\dot.ts
-    format the codes
> add the dot.ts in basic pakcage and format the codes

- CONTRIBUTING.md
- examples/main.ts
- mods/mod-chart/package.json
- mods/mod-chart/src/index.ts
- mods/mod-chart/src/utils/chartData.ts
- mods/mod-chart/src/utils/chartStyle.ts
- mods/mod-chart/src/utils/chartUtil.ts
- mods/mod-chart/src/utils/index.ts
- mods/mod-chart/src/widgets/barChart.ts
- mods/mod-chart/src/widgets/chartDataUnit.ts
- mods/mod-chart/src/widgets/chartLayout.ts
- mods/mod-chart/src/widgets/index.ts
- mods/mod-geometry/src/widgets/brace.ts
- packages/basic/src/widgets/figures/arc.ts
- packages/basic/src/widgets/figures/line.ts
- packages/basic/src/widgets/figures/path.ts
- packages/basic/src/widgets/figures/polygon.ts
- packages/basic/src/widgets/figures/rect.ts
- pnpm-lock.yaml
**Description:** 
- feat: `BarChart`;
- fix: typo;
- fix: color alpha
**Checklist:**
> feat: `BarChart`; fix: typo; fix: color alpha

- examples/main.ts
- mods/mod-chart/src/widgets/barChart.ts
- mods/mod-chart/src/widgets/chartLayout.ts
- mods/mod-chart/src/widgets/lineChart.ts
- fix: correct position of xLabels for `BarChart` and correct position of yLabels for `LineChart` in `indexAxis: 'y'`
- feat: add negative value support for `BarChart` and `LineChart`
- fix: correct yLabel position for `BarChart` in `indexAxis: 'y'`
**Checklist:**
**Screenshots:**
> feat: add negative value support for `BarChart` and `LineChart`

- mods/mod-chart/src/widgets/lineChart.ts
**Description:** feat: add antiAlias support for `LineChart`
**Checklist:**
**Screenshots:**
> feat: add antiAlias support for `LineChart`

- examples/chart.test.mjs
- mods/mod-chart/src/widgets/barChart.ts
- mods/mod-chart/src/widgets/lineChart.ts
- mods/mod-chart/src/widgets/mixedChart.ts
fix(mod-chart): enabled chart widget to work in local mode
**Checklist:**
**Screenshots:**
> fix(mod-chart): enabled chart widget to work in local mode

- examples/main.ts
- mods/mod-chart/src/widgets/barChart.ts
- mods/mod-chart/src/widgets/baseChart.ts
- mods/mod-chart/src/widgets/chartLayout.ts
- mods/mod-chart/src/widgets/lineChart.ts
- mods/mod-geometry/src/widgets/angle.ts
- mods/mod-geometry/src/widgets/brace.ts
- mods/mod-math/src/widgets/mathFunction.ts
- packages/basic/src/widgets/figures/arc.ts
- packages/basic/src/widgets/figures/arrow.ts
- packages/basic/src/widgets/figures/figure.ts
- packages/basic/src/widgets/figures/line.ts
- packages/basic/src/widgets/figures/path.ts
- packages/basic/src/widgets/figures/polygon.ts
- packages/basic/src/widgets/figures/rect.ts
- packages/basic/src/widgets/text.ts
- feat: add Shader support for widgets
- fix(basic): correct wrong Color transform
- fix(mod-chart): correct behavior on `gridAlign`
**Checklist:**
> feat: add Shader support for widgets

- mods/mod-chart/src/widgets/lineChart.ts
- perf(mod-chart): avoid crate new ck.Path when update Path
**Checklist:**
> perf(mod-chart): avoid crate new ck.Path when update Path

- packages/core/src/global.ts
---
---
**TODO**
**Checklist:**
> chore: delete fps because it not support

- examples/main.ts
- pnpm-lock.yaml
---
---
**Description:** Be careful doing these deletion and remember to run `build` each commit
> chore: delete `fps` completely

- mods/mod-chart/src/widgets/lineChart.ts
- mods/mod-geometry/src/widgets/angle.ts
- mods/mod-geometry/src/widgets/brace.ts
- mods/mod-math/src/widgets/mathFunction.ts
- packages/basic/src/widgets/figures/arc.ts
- packages/basic/src/widgets/figures/arrow.ts
- packages/basic/src/widgets/figures/line.ts
- packages/basic/src/widgets/figures/path.ts
- packages/basic/src/widgets/figures/polygon.ts
- packages/basic/src/widgets/figures/rect.ts
- packages/core/src/widget.ts
- perf: use `ck.Path.contains` to fulfill `isIn`
- feat(core): add default `isIn` implement for child widgets.
- feat(core): `Widget.transformedPoint` for coordinate transform
- feat: add `isIn` implementation for widgets with `path`
**Checklist:**
> feat: default `isIn` implementation, `Widget.transformedPoint` and `isIn` implementation for widgets with `path`

- mods/mod-chart/src/widgets/lineChart.ts
- mods/mod-geometry/src/widgets/brace.ts
- mods/mod-math/src/widgets/mathFunction.ts
- packages/basic/src/widgets/figures/arc.ts
- packages/basic/src/widgets/figures/arrow.ts
- packages/basic/src/widgets/figures/line.ts
- packages/basic/src/widgets/figures/path.ts
- packages/basic/src/widgets/figures/polygon.ts
- packages/basic/src/widgets/figures/rect.ts
- packages/basic/src/widgets/imageWidget.ts
- packages/basic/src/widgets/svg.ts
- packages/basic/src/widgets/text.ts
- packages/core/src/widget.ts
- refactor(core): add `Widget.calculateIn`
- feat: `calculateIn` for widgets
**Checklist:**
> refactor(core): add `Widget.calculateIn`

- docs/content/dev/advanced-widget.md
- docs/content/dev/basic-widget.md
- docs/content/zh/dev/advanced-widget.md
- docs/content/zh/dev/basic-widget.md
- docs: add `calculateIn` and `calculateRange` explanation
**Checklist:**
> docs: add `calculateIn` and `calculateRange` explanation

- packages/basic/src/widgets/figures/arc.ts
- packages/basic/src/widgets/figures/figure.ts
- packages/basic/src/widgets/figures/line.ts
- packages/basic/src/widgets/figures/path.ts
- packages/basic/src/widgets/figures/polygon.ts
- packages/basic/src/widgets/figures/rect.ts
- refactor(basic): Widget based on path now inherit from the `Path`
**Checklist:**
> refactor(basic): Widget based on path now inherit from the `Path`

- examples/main.ts
- mods/mod-chart/src/widgets/barChart.ts
- packages/basic/src/widgets/figures/rect.ts
- feat(basic): add `radius` for `Rect`
**Checklist:**
> feat(basic): add `radius` for `Rect`

- packages/basic/src/widgets/figures/arrow.ts
> fix(basic): fix trim invisible in `Arrow`

- examples/main.ts
- mods/mod-chart/src/widgets/baseSimpleChart.ts
- mods/mod-chart/src/widgets/chartLayout.ts
- mods/mod-chart/src/widgets/lineChart.ts
- packages/basic/src/widgets/text.ts
feat(mod-chart): now legends can be relayed based on real text width
feat(basic): add `getLineMetrics` method
---
---
**TODO**
**Checklist:**
> feat(mod-chart): add animation for `ChartLayout`

- packages/core/src/patch.ts
- packages/utils/src/judgements.ts
- packages/utils/src/object.ts
---
---
**TODO**
**Checklist:**
> fix: Improved `patch` for performance

- cli/src/build/index.ts
- pnpm-lock.yaml
---
---
**TODO**
**Checklist:**
> fix(cli): generated video duration is 0

- docs/content/zh/basic/setup.md
---
---
**TODO**
**Checklist:**
> docs :update setup_zh

- docs/content/zh/basic/unit.md
---
---
**Description:** docs: translate unit.md to chinese
**TODO**
**Checklist:**
> docs: translate unit.md to chinese

- docs/content/zh/basic/update-function.md
---
---
**Description:** docs: translate update-function.md to chinese
**TODO**
**Checklist:**
> docs: translate update-function.md to chinese
